### ISSUE TITLE
"Timer was not added to the SceneTree" issue and possible fix

### ISSUE THREAD

**Issue by hydescarf** [MakovWait/godot-script-tabs#3]
Every time when the editor is launched with the plugin on by default, the issue "Timer was not added to the SceneTree" will come up to the debugger. Sometimes it also comes out when switching tabs.

After a few trial and errors, the signal `item_selected` seems to be the culprit behind this. To workaround it, I tried out with a `call_deferred` for that signal and it worked.
```gdscript
func _on_tab_selected(tab_idx):
	_last_tab_selected = tab_idx
	var item_idx = _find_list_item_idx_by_tab_idx(tab_idx)
	if item_idx != -1:
		if not _scripts_item_list.is_selected(item_idx):
			select_item_deferred.call_deferred(item_idx) # this part is changed to a method below to be call_deferred

func select_item_deferred( item_idx ):
	_scripts_item_list.select(item_idx)
	_scripts_item_list.item_selected.emit(item_idx)
```

This could be a bandage fix, I'm not too sure but at least it works without error now.

**Comment by MakovWait** [comment]
thanks!
