### ISSUE TITLE
Errors when reloading project or closing tabs

### ISSUE THREAD

**Issue by Hilderin** [MakovWait/godot-script-tabs#4]
Godot 4.2.1 (Linux and Windows)
When I had scripts openned and i restart godot, I get this error. All is working fine, tabs are there and everything:
![image](https://github.com/MakovWait/godot-script-tabs/assets/81109165/d764505e-9ccf-4196-80c9-43a48e650d8a)

I right click on a tab and select Close All. Now I have these errors:
![image](https://github.com/MakovWait/godot-script-tabs/assets/81109165/33cd776e-e814-4556-a528-c8b6ec7d327d)

For now, i just disable "Reload Scripts on load" and I no error on load and when i close tabs

**Comment by MakovWait** [comment]
should be fixed in the github version. queued update to AssetLib, it will be available in a few days.

**Comment by Hilderin** [comment]
Thank you so much! I confirm, it's working fine now. Thanks again and thanks for this addon.
